version: '3.9'
services:
  # Ollama Service
  ollama:
    image: ollama/ollama:0.11.4
    pull_policy: if_not_present
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama/ollama.json:/root/.ollama/ollama.json
    networks:
      - ollama_network
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_DEBUG=1
      - OLLAMA_KEEP_ALIVE=60m
      - OLLAMA_VERBOSE=1
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_NUM_CTX=16384
      - OLLAMA_NUM_THREAD=8
      - OLLAMA_MLOCK=false
      - OLLAMA_NUM_BATCH=512  # Higher value for better performance
    shm_size: 4gb  # Increase from default 64MB to 1GB
    oom_kill_disable: true
    command: serve
    mem_limit: 36G
    mem_reservation: 16G
    ulimits:
      memlock: -1  # Unlimited locked memory    

  proxy:
    build: .
    restart: unless-stopped
    environment:
      - API_KEY=${API_KEY}
      - OLLAMA_URL=${OLLAMA_URL:-http://ollama:11434}
    depends_on:
      - ollama
    networks:
      - ollama_network

  # Cloudflared Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    networks:
      - ollama_network
    volumes:
      - ./cloudflare:/etc/cloudflared
    command: tunnel --no-autoupdate run
    depends_on:
      - proxy

volumes:
  ollama_data:

networks:
  ollama_network: