version: '3.9'
services:
  # gemma3 27b q5 Setup (unverändert aus deiner bestehenden Konfiguration)
  gemma3_27b_q5_ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - gemma3_27b_q5_data:/root/.ollama
      - ./ollama.json:/root/.ollama/ollama.json
    networks:
      - gemma3_27b_q5_network
    environment:
      - OLLAMA_DEBUG=1
      - OLLAMA_VERBOSE=1
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_NUM_PARALLEL=1
    shm_size: 4gb  # Increase from default 64MB to 1GB
    oom_kill_disable: true
    command: serve
    deploy:
      resources:
        limits:
          memory: 30G
        reservations:
          memory: 16G
          devices:
            - driver: nvidia
              count: 1  # Nur 1 GPU verwenden
              capabilities: [gpu]
    ulimits:
      memlock: -1  # Unlimited locked memory    

  gemma3_27b_q5_proxy:
    build: ..
    restart: unless-stopped
    ports:
      - "30006:3000"
    environment:
      - API_KEY=5az5z9IGZKjT54nroc1jUQrp7O8Cc7w4xkEuNcAHhvAYBKY8Y9rVa14kkRfS888z
      - OLLAMA_URL=http://gemma3_27b_q5_ollama:11434
    depends_on:
      - gemma3_27b_q5_ollama
    networks:
      - gemma3_27b_q5_network

  # Cloudflared Tunnel
  gemma3_27b_q5_cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    networks:
      - gemma3_27b_q5_network
    volumes:
      - ./cloudflared-config:/etc/cloudflared
    command: tunnel --no-autoupdate run
    depends_on:
      - gemma3_27b_q5_proxy

volumes:
  gemma3_27b_q5_data:

networks:
  gemma3_27b_q5_network: