version: '3.9'
services:
  # model4 Setup (unverändert aus deiner bestehenden Konfiguration)
  model4_ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - model4_data:/root/.ollama
      - ./ollama.json:/root/.ollama/ollama.json
    networks:
      - model4_network
    environment:
      - OLLAMA_DEBUG=1
      - OLLAMA_VERBOSE=1
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_NUM_PARALLEL=1
    shm_size: 4gb  # Increase from default 64MB to 1GB
    oom_kill_disable: true
    command: serve
    deploy:
      resources:
        limits:
          memory: 30G
        reservations:
          memory: 16G
          devices:
            - driver: nvidia
              count: 1  # Nur 1 GPU verwenden
              capabilities: [gpu]
    ulimits:
      memlock: -1  # Unlimited locked memory    

  model4_proxy:
    build: ..
    restart: unless-stopped
    ports:
      - "30004:3000"
    environment:
      - API_KEY=Db83Evhoq176ge5e34C2D8lc682BlmC1OsRz9vC9xm38XV0xp8ynFB3o8y1OOkau
      - OLLAMA_URL=http://model4_ollama:11434
    depends_on:
      - model4_ollama
    networks:
      - model4_network

  # Cloudflared Tunnel
  model4_cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    networks:
      - model4_network
    volumes:
      - ./cloudflared-config:/etc/cloudflared
    command: tunnel --no-autoupdate run
    depends_on:
      - model4_proxy

volumes:
  model4_data:

networks:
  model4_network: