version: '3.9'
services:
  # Gemma 4B Setup (unverändert aus deiner bestehenden Konfiguration)
  gemma3_4b_ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - gemma3_4b_data:/root/.ollama
      - ./ollama.json:/root/.ollama/ollama.json
    networks:
      - gemma3_4b_network
    environment:
      - OLLAMA_DEBUG=1
      - OLLAMA_VERBOSE=1
      - OLLAMA_HOST=0.0.0.0:11434
    shm_size: 4gb  # Increase from default 64MB to 1GB
    oom_kill_disable: true
    command: serve
    deploy:
      resources:
        limits:
          memory: 20G
        reservations:
          memory: 12G
    ulimits:
      memlock: -1  # Unlimited locked memory    

  gemma3_4b_proxy:
    build: ..
    restart: unless-stopped
    ports:
      - "30001:3000"
    environment:
      - API_KEY=v2SBxsS5D2N0XqL981Hf4J785n99kHCLtevCD0h8Z3cuIbhJjyt08MCapF6617E6
      - OLLAMA_URL=http://gemma3_4b_ollama:11434
    depends_on:
      - gemma3_4b_ollama
    networks:
      - gemma3_4b_network

  # Cloudflared Tunnel
  gemma3_4b_cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    networks:
      - gemma3_4b_network
    volumes:
      - ./cloudflared-config:/etc/cloudflared
    command: tunnel --no-autoupdate run
    depends_on:
      - gemma3_4b_proxy

volumes:
  gemma3_4b_data:

networks:
  gemma3_4b_network: