version: '3.9'
services:
  # Gemma 4B Setup (unverändert aus deiner bestehenden Konfiguration)
  gemma3_4b_ollama:
    image: ollama/ollama:latest
    volumes:
      - gemma3_4b_data:/root/.ollama
    networks:
      - gemma3_4b_network
    command: serve

  gemma3_4b_proxy:
    build: ..
    ports:
      - "30001:3000"
    environment:
      - API_KEY=${API_KEY_4B}
      - OLLAMA_URL=http://gemma3_4b_ollama:11434
    depends_on:
      - gemma3_4b_ollama
    networks:
      - gemma3_4b_network

  # Cloudflared Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    networks:
      - gemma3_4b_network
    volumes:
      - ./cloudflared-config:/etc/cloudflared
    command: tunnel --no-autoupdate run
    depends_on:
      - gemma3_4b_proxy

volumes:
  gemma3_4b_data:

networks:
  gemma3_4b_network: