tunnel: a4f5b3c7-1f0a-4c6a-8b24-62ee826a7dcb
credentials-file: /etc/cloudflared/a4f5b3c7-1f0a-4c6a-8b24-62ee826a7dcb.json
ingress:
  - hostname: gemma3-12b.scribomate.ai
    service: http://gemma3_12b_proxy:3000
  - service: http_status:404